sudo: false
language: nix

addons:
  apt:
    packages:
    - gnutls-bin
    - sharutils
    - gnupg2
    - python-minimal
    - python-setuptools
    - python-pip
    - python3-minimal
    - python3-pip
    - python3-setuptools
    - dirmngr

cache:
  directories:
  - $HOME/local
  - $HOME/.cask
  - $HOME/.cache/pip
  - $HOME/.evm
  - $HOME/.emacs.d
  - $HOME/Library/Caches/Homebrew
  - $HOME/.pyenv
  - $HOME/Library/Caches/pip

env:
  global:
    - PATH=$HOME/local/bin:$HOME/local/evm/bin:$HOME/local/cask/bin:$PATH

matrix:
  allow_failures:
    - env: EMACS_CI=emacs-snapshot
  include:
    - os: linux
      env: EMACS_CI=emacs-25-1 PY=python PIP="${PY} -m pip install --user"
    - os: linux
      env: EMACS_CI=emacs-26-2 PY=python3 PIP="${PY} -m pip install --user"
    - os: osx
      env: EMACS_CI=emacs-26-3 PY=python PIP="pip install" TOXENV=py27

install:
  - sh tools/install-virtualenv.sh
  - |
    if [ "x$TRAVIS_OS_NAME" = "xosx" ]; then
      eval "$(pyenv init -)"
      pyenv activate $TOXENV
    fi
  - ${PIP} --upgrade pip
  - ${PIP} wheel pylint pytest
  - ${PIP} -r requirements-dev.txt

before_script:
  - bash tools/travis-install
  - emacs --version
  - sh tools/install-cask.sh

script:
  - PYTHON=${PY} make test-venv
  - PYTHON=${PY} make test-run
  - PYTHON=${PY} make test || ( ( printf "To diagnose, travis logs -i | dos2unix | sed '/^begin 644/,/^end/!d' | uudecode\n" ) && ( zip -q - tests/log/* 2>/dev/null | uuencode log.zip ) && false)
